### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by Xu1103** [langmanbusi/Semantic-Aware-Low-Light-Image-Enhancement#29]
配置好pytorch为1.8.0后，运行DRBN_SKF的测试数据时出错，Traceback (most recent call last):
  File "main_test.py", line 4, in <module>
    import data
  File "/Projects_xkh/Semantic-Aware-Low-Light-Image-Enhancement-main/DRBN_SKF/src/data/__init__.py", line 3, in <module>
    from dataloader import MSDataLoader
  File "/Projects_xkh/Semantic-Aware-Low-Light-Image-Enhancement-main/DRBN_SKF/src/dataloader.py", line 13, in <module>
    from torch.utils.data.dataloader import _DataLoaderIter
ImportError: cannot import name '_DataLoaderIter' from 'torch.utils.data.dataloader'，请问这个环境版本过高的问题该怎么解决啊？

**Comment by langmanbusi** [comment]
可以把这个类复制进去，我就是这么干的
https://github.com/pytorch/pytorch/blob/0b868b19063645afed59d6d49aff1e43d1665b88/torch/utils/data/dataloader.py#L199

**Comment by Xu1103** [comment]
方便分享一下您已经训练好的模型吗？想试试效果，感谢感谢！
